# GitHub Actions Workflow for Building Minecraft Mod with Fabric
name: Build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        minecraft: [1.20.1]
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Validate the Gradle wrapper to prevent tampering
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # 3. Set up JDK 17 (required for Minecraft mod development)
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 4. Ensure the Gradle wrapper script is executable (Ubuntu/Linux issue)
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # 5. Configure and setup the project for the Minecraft version
      - name: Setup Minecraft Version ${{ matrix.minecraft }}
        run: ./gradlew setupFiles -PbuildVersion="${{ matrix.minecraft }}"

      # 6. Build the project for the matrix version of Minecraft
      - name: Build Project for Minecraft ${{ matrix.minecraft }}
        run: ./gradlew build -PbuildVersion="${{ matrix.minecraft }}"
      
      # 7. Capture release artifacts after building
      - name: Upload Release Artifacts for ${{ matrix.minecraft }}
        uses: actions/upload-artifact@v3
        with:
          name: Fabric Artifacts (MC ${{ matrix.minecraft }})
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
